### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by TML007** [boai/BAWeChat#1]
diff: /Users/sks/Downloads/BAWeChat-master/原生微信/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by boai** [comment]
你先 执行： pod setup 更新下本地的pod spec 库，然后再 执行：pod update --verbose --no-repo-update 更新pod，然后再运行！
