### ISSUE TITLE
SDWebImageDownloaderOperation 报错

### ISSUE THREAD

**Issue by RenSihao** [boai/BAWeChat#7]
pod 之后运行，SDWebImageDownloaderOperation.m 46行 47行报错未定义。。。

**Comment by boai** [comment]
你 更新你的 pod setup，用最新的pod运行

**Comment by RenSihao** [comment]
ok啦 ！thx ~ MLLabel.m 24行 😁

**Comment by boai** [comment]
嗯，有issue 和 需求都可以跟我提，readme 有联系方式
